### ISSUE TITLE
Invisible Obsidian Pressure Plate recipe seems overpowered. Probably needs a balancing patch.

### ISSUE THREAD

**Issue by ALPHANUMERIC1** [Gaz492/Player-Plates#3]
As I stated in the title of this issue, the Invisible Obsidian Pressure Plate recipe seems a bit overpowered. It may need a balancing patch of some sort. Beyond that, this mod seems interesting enough and I intend to follow its development in the future.

**Comment by Gaz492** [comment]
Do you have any suggestions for an alternative recipe?
 I did consider using a potion of invisibility initially but decided against it as I know slot of people are not a fan of brewing potions.
